export interface Service {
  id: string;
  title: string;
  description: string;
  icon: string;
  details: string[];
  featured?: boolean;
  subServices?: Service[];
  heroDescription?: string;
  longDescription?: string;
  benefits?: string[];
  process?: string[];
  seoTitle?: string;
  seoDescription?: string;
}

export const services: Service[] = [
  {
    id: "children-dentistry",
    title: "Children's Dentistry",
    description: "Gentle care for little smiles",
    icon: "child",
    details: [
      "Gentle first visits and dental exams",
      "Habit-building and oral hygiene education",
      "Child-friendly tools and techniques",
      "Rewards program with toys and stickers",
      "Preventive sealants and fluoride",
    ],
    heroDescription: "Creating positive dental experiences for children with gentle, compassionate care that builds lifelong healthy habits.",
    longDescription: "At Family First Smile Care, we understand that a child's first dental experiences shape their relationship with oral health for life. Our pediatric approach focuses on creating a welcoming, fun environment where children feel safe and comfortable.",
    benefits: [
      "Child-friendly environment with toys and games",
      "Gentle techniques designed for young patients",
      "Educational approach to build healthy habits",
      "Preventive focus to avoid future problems",
      "Positive reinforcement and reward systems",
    ],
    process: [
      "Initial consultation and comfort visit",
      "Gentle examination and assessment",
      "Fun educational activities about oral health",
      "Professional cleaning if appropriate",
      "Home care instructions for parents",
    ],
    subServices: [
      {
        id: "childrens-dentistry/babys-first-visit",
        title: "Baby's First Visit",
        description: "Gentle, parent-involved dental visits for infants and toddlers",
        icon: "child",
        details: [
          "Knee-to-knee exams with parents present",
          "Teething and feeding guidance",
          "Age-appropriate cleanings and fluoride",
        ],
        heroDescription: "A warm, unrushed introduction to dental care where parents stay close and babies feel secure.",
        longDescription: "We pace baby visits slowly, letting little ones explore while we coach parents on brushing, nutrition, and soothing techniques.",
        benefits: [
          "Positive first impressions of dental care",
          "Personalized coaching for home routines",
          "Early detection of tongue or lip ties",
        ],
        process: [
          "Warm welcome and comfort visit",
          "Knee-to-knee exam with a parent",
          "Gentle cleaning and fluoride if recommended",
          "Customized home-care plan",
        ],
        seoTitle: "Baby's First Dental Visit in Los Gatos, CA | Family First Smile Care",
        seoDescription: "A calm, playful first dental visit for babies in Los Gatos. Learn what happens, how to prepare, and why early visits matter for lifelong oral health.",
      },
    ],
  },
  {
    id: "dental-exams",
    title: "Dental Exams",
    description: "Comprehensive oral health evaluations",
    icon: "tooth",
    details: [
      "Thorough oral health examinations",
      "Digital X-rays and imaging",
      "Early detection of dental issues",
      "Personalized treatment planning",
      "Regular check-up recommendations",
    ],
    heroDescription: "Comprehensive dental examinations using advanced technology to detect issues early and maintain optimal oral health.",
    longDescription: "Regular dental examinations are the foundation of preventive oral healthcare. Our thorough evaluations help identify potential issues before they become serious problems, saving you time, discomfort, and expense.",
    benefits: [
      "Early detection prevents major problems",
      "Digital imaging for precise diagnosis",
      "Personalized treatment recommendations",
      "Comprehensive oral health assessment",
      "Professional guidance and education",
    ],
    process: [
      "Medical and dental history review",
      "Visual examination of teeth and gums",
      "Digital X-rays if needed",
      "Oral cancer screening",
      "Treatment planning discussion",
    ],
  },
  {
    id: "dental-hygiene",
    title: "Dental Hygiene",
    description: "Professional cleanings and education",
    icon: "sparkles",
    details: [
      "Professional dental cleanings",
      "Plaque and tartar removal",
      "Gum health assessment",
      "Personalized oral hygiene education",
      "Home care recommendations",
    ],
    heroDescription: "Professional dental cleanings and personalized hygiene education to maintain healthy teeth and gums.",
    longDescription: "Professional dental hygiene services go beyond what you can achieve at home. Our skilled hygienists provide thorough cleanings while educating you on the best practices for maintaining optimal oral health.",
    benefits: [
      "Removes hardened plaque and tartar",
      "Prevents gum disease and cavities",
      "Fresh breath and clean feeling",
      "Personalized hygiene instruction",
      "Early detection of oral health issues",
    ],
    process: [
      "Gum health evaluation",
      "Professional plaque and tartar removal",
      "Deep cleaning and polishing",
      "Fluoride treatment if recommended",
      "Home care instruction and tips",
    ],
  },
  {
    id: "family-dentistry",
    title: "General & Family Dentistry",
    description: "Comprehensive care for all ages",
    icon: "tooth",
    details: [
      "Routine dental examinations",
      "Professional dental cleanings",
      "Preventive care and education",
      "Digital X-rays and diagnostics",
      "Fluoride treatments",
    ],
    heroDescription: "Complete dental care for every member of your family, from children to seniors, in one convenient location.",
    longDescription: "Family dentistry means comprehensive care for patients of all ages. We provide everything from routine cleanings to complex treatments, ensuring your entire family receives consistent, quality dental care.",
    benefits: [
      "Convenient care for the whole family",
      "Consistent treatment philosophy",
      "Comprehensive range of services",
      "Family-friendly environment",
      "Long-term oral health relationships",
    ],
    process: [
      "Initial family consultation",
      "Individual treatment planning",
      "Preventive care focus",
      "Regular maintenance visits",
      "Ongoing oral health education",
    ],
  },
  {
    id: "night-guards",
    title: "Night Guards",
    description: "Protection against teeth grinding",
    icon: "tooth",
    details: [
      "Custom-fitted night guards",
      "Protection against bruxism",
      "Comfortable, durable materials",
      "Reduced jaw tension and pain",
      "Prevents tooth wear and damage",
    ],
    heroDescription: "Custom-fitted night guards to protect your teeth from grinding and clenching while you sleep.",
    longDescription: "Teeth grinding (bruxism) can cause significant damage to your teeth and jaw over time. Our custom night guards provide comfortable protection while you sleep, preventing wear and reducing associated pain.",
    benefits: [
      "Prevents tooth wear and damage",
      "Reduces jaw pain and tension",
      "Improves sleep quality",
      "Custom fit for maximum comfort",
      "Durable, long-lasting protection",
    ],
    process: [
      "Bruxism evaluation and assessment",
      "Custom impressions for perfect fit",
      "Night guard fabrication",
      "Fitting and adjustment appointment",
      "Follow-up care and maintenance",
    ],
  },
  {
    id: "restorative-dentistry",
    title: "Restorative Dentistry",
    description: "Restore damaged teeth to full function",
    icon: "tooth",
    details: [
      "Composite fillings",
      "Dental bonding",
      "Root canal therapy",
      "Complete smile restoration",
      "Long-lasting, natural-looking results",
    ],
    heroDescription: "Advanced restorative treatments to repair damaged teeth and restore your smile to optimal function and beauty.",
    longDescription: "Restorative dentistry encompasses treatments that repair, replace, or restore damaged teeth. Our goal is to preserve your natural teeth whenever possible while ensuring optimal function and aesthetics.",
    benefits: [
      "Preserves natural tooth structure",
      "Restores full chewing function",
      "Natural-looking results",
      "Long-lasting durability",
      "Prevents further damage",
    ],
    process: [
      "Comprehensive examination and diagnosis",
      "Treatment planning discussion",
      "Preparation and restoration",
      "Final adjustments and polish",
      "Follow-up care instructions",
    ],
    subServices: [
      {
        id: "invisalign",
        title: "Invisalign",
        description: "Clear aligners for a perfect smile",
        icon: "smile",
        featured: true,
        details: [
          "Virtually invisible clear aligners",
          "Removable for eating and cleaning",
          "Comfortable, smooth plastic material",
          "Shorter treatment time than traditional braces",
          "Free initial consultation with iTero\u00ae 3D digital scan and smile preview",
        ],
        heroDescription: "Straighten your teeth discreetly with Invisalign clear aligners - the modern alternative to traditional braces.",
        longDescription: "Invisalign uses a series of custom-made, clear aligners to gradually move your teeth into the desired position. The aligners are virtually invisible and can be removed for eating, brushing, and special occasions.",
        benefits: [
          "Nearly invisible treatment",
          "Removable for convenience",
          "More comfortable than braces",
          "Faster treatment time",
          "Easy maintenance and cleaning",
        ],
        process: [
          "Free consultation + iTero\u00ae 3D digital scan",
          "Custom treatment plan creation",
          "Aligner fabrication and delivery",
          "Regular progress check-ups",
          "Retainer fitting after completion",
        ],
        seoTitle: "Invisalign Los Gatos | iTero Scan | Family First Smile Care",
        seoDescription: "Invisalign in Los Gatos. Our iTero\u00ae digital scanner takes a fast, comfortable 3D scan (no messy impressions) and helps preview your smile. Book a consultation.",
      },
      {
        id: "teeth-whitening",
        title: "Teeth Whitening",
        description: "Professional whitening for brighter smiles",
        icon: "sparkles",
        details: [
          "Professional-grade whitening treatments",
          "Safe and effective bleaching agents",
          "Dramatic results in just one visit",
          "Custom take-home whitening kits",
          "Long-lasting, natural-looking brightness",
        ],
        heroDescription: "Professional teeth whitening treatments that deliver safe, dramatic results for a brighter, more confident smile.",
        longDescription: "Professional teeth whitening is one of the most popular cosmetic dental treatments. Our safe, effective whitening systems can brighten your smile by several shades in just one appointment.",
        benefits: [
          "Professional-strength whitening agents",
          "Safe, supervised treatment",
          "Dramatic, immediate results",
          "Customized to your needs",
          "Long-lasting brightness",
        ],
        process: [
          "Consultation and shade assessment",
          "Professional cleaning if needed",
          "Whitening treatment application",
          "Progress monitoring during treatment",
          "Take-home maintenance kit",
        ],
      },
      {
        id: "dental-crowns",
        title: "Dental Crowns",
        description: "Restore and protect damaged teeth",
        icon: "tooth",
        details: [
          "Custom-fitted porcelain crowns",
          "Natural-looking tooth restoration",
          "Strong, durable materials",
          "Same-day crown options available",
          "Complete protection for damaged teeth",
        ],
        heroDescription: "Custom dental crowns that restore damaged teeth to full function while maintaining a natural, beautiful appearance.",
        longDescription: "Dental crowns are tooth-shaped caps that completely cover a damaged tooth above the gum line. They restore the tooth's shape, size, strength, and improve its appearance while providing long-lasting protection.",
        benefits: [
          "Complete tooth protection",
          "Natural appearance and feel",
          "Durable, long-lasting materials",
          "Restores full chewing function",
          "Same-day options available",
        ],
        process: [
          "Tooth preparation and impression",
          "Temporary crown placement",
          "Custom crown fabrication",
          "Final crown fitting and adjustment",
          "Care instructions and follow-up",
        ],
      },
    ],
  },
  {
    id: "tmj",
    title: "TMJ Treatment",
    description: "Relief for jaw pain and dysfunction",
    icon: "activity",
    details: [
      "Comprehensive TMJ/TMD evaluation and diagnosis",
      "Custom night guards to prevent teeth grinding",
      "Physical therapy and jaw exercises",
      "Advanced CBCT imaging for precise assessment",
      "Personalized treatment plans for lasting relief",
    ],
  },
];
